openapi: 3.0.0
info:
  title: MSCS721 Concordance
  description: A simple concordance API.
  contact:
    email: michael.gildein1@marist.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
- url: https://virtserver.swaggerhub.com/mscs721/concordance/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: analysis
  description: Operations available for text analysis
paths:
  /nltk:
    post:
      tags:
      - nltk
      summary: Calculate
      description: Post text to generate concordance
      operationId: getNtlk
      requestBody:
        description: Text to be analyzed
        content:
          text/plain:
            schema:
              type: string
            example: The brown fox jumped over the brown log.
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/concordance_result'
        "400":
          description: invalid input, object invalid
      x-swagger-router-controller: Nltk
  /locate:
    post:
      tags:
      - locate
      summary: Calculate
      description: Post text to generate locations
      operationId: getLocations
      requestBody:
        description: Text to be analyzed
        content:
          text/plain:
            schema:
              type: string
            example: The brown fox jumped over the brown log.
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location_result'
        "400":
          description: invalid input, object invalid
      x-swagger-router-controller: Locate
  /analyze:
    post:
      tags:
      - analysis
      summary: Calculate
      description: Post text to generate concordance
      operationId: getConcordance
      requestBody:
        description: Text to be analyzed
        content:
          text/plain:
            schema:
              type: string
            example: The brown fox jumped over the brown log.
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/concordance_result'
        "400":
          description: invalid input, object invalid
      x-swagger-router-controller: Analysis
components:
  schemas:
    concordance_result:
      required:
      - concordance
      - input
      type: object
      properties:
        concordance:
          type: array
          example:
          - token: brown
            count: 2
          - token: fox
            count: 1
          - token: jumped
            count: 1
          - token: log
            count: 1
          - token: over
            count: 1
          - token: the
            count: 1
          items:
            $ref: '#/components/schemas/concordance_result_concordance'
        input:
          type: string
          example: The brown fox jumped over the brown log.
      example:
        input: The brown fox jumped over the brown log.
        concordance:
        - token: brown
          count: 2
        - token: fox
          count: 1
        - token: jumped
          count: 1
        - token: log
          count: 1
        - token: over
          count: 1
        - token: the
          count: 1
    location_result:
      required:
      - input
      - location
      type: object
      properties:
        location:
          type: array
          example:
          - token: brown
            locations:
            - 1
            - 6
          - token: fox
            locations:
            - 2
          - token: jumped
            locations:
            - 3
          - token: log
            locations:
            - 7
          - token: over
            locations:
            - 4
          - token: the
            locations:
            - 0
            - 5
          items:
            $ref: '#/components/schemas/location_result_location'
        input:
          type: string
          example: The brown fox jumped over the brown log.
      example:
        input: The brown fox jumped over the brown log.
        location:
        - token: brown
          locations:
          - 1
          - 6
        - token: fox
          locations:
          - 2
        - token: jumped
          locations:
          - 3
        - token: log
          locations:
          - 7
        - token: over
          locations:
          - 4
        - token: the
          locations:
          - 0
          - 5
    nltk_result:
      required:
      - concordance
      - input
      type: object
      properties:
        concordance:
          type: array
          example:
          - token: brown
            count: 2
          - token: fox
            count: 1
          - token: jumped
            count: 1
          - token: log
            count: 1
          - token: over
            count: 1
          - token: the
            count: 1
          items:
            $ref: '#/components/schemas/concordance_result_concordance'
        input:
          type: string
          example: The brown fox jumped over the brown log.
      example:
        input: The brown fox jumped over the brown log.
        concordance:
        - token: brown
          count: 2
        - token: fox
          count: 1
        - token: jumped
          count: 1
        - token: log
          count: 1
        - token: over
          count: 1
        - token: the
          count: 1
    concordance_result_concordance:
      type: object
      properties:
        token:
          type: string
        count:
          type: integer
    location_result_location:
      type: object
      properties:
        token:
          type: string
        locations:
          type: array
          items:
            type: integer
    nltk_result_concordance:
      type: object
      properties:
        token:
          type: string
        count:
          type: integer